# <center> Working with Dictionary and DataFrame </center>

## 1) Working With dictionary

# 1.1) Creating Dictionary

In [129]:
student = {
    "name" : "oshan",
    "roll_no" : 230328,
    "age" : 22,
    "facality" : "BCE"

}

# 1.2) Access value of Dictionary

In [130]:
print (student["name"])

oshan

# 1.2) Use Get

In [131]:
student.get("name")

'oshan'

# 1.3) Add item

In [132]:
student["phone_no"] = 97416635741
student

{'name': 'oshan',
 'roll_no': 230328,
 'age': 22,
 'facality': 'BCE',
 'phone_no': 97416635741}

# 1.4) Update value

In [133]:
student["roll_no"]= 28
student

{'name': 'oshan',
 'roll_no': 28,
 'age': 22,
 'facality': 'BCE',
 'phone_no': 97416635741}

# 1.5) Delete value using del

In [134]:
del student["phone_no"]
student

{'name': 'oshan', 'roll_no': 28, 'age': 22, 'facality': 'BCE'}

# 1.6) Remove using pop

In [135]:
student.pop("facality")
student

{'name': 'oshan', 'roll_no': 28, 'age': 22}

# 1.7) Automatic remove item using popitem(remove from last)

In [136]:
student.popitem()
student

{'name': 'oshan', 'roll_no': 28}

# 1.8) Copy Dict

In [137]:
copyStudent = student.copy()
copyStudent

{'name': 'oshan', 'roll_no': 28}

# 1.9)Get All Keys

In [138]:
student.keys()

dict_keys(['name', 'roll_no'])

# 1.10)Get All Values

In [139]:
student.values()

dict_values(['oshan', 28])

# 1.11) Clear Dictionary

In [140]:
copyStudent.clear()
copyStudent

{}

# 1.12) Get All Items

In [141]:
student.items()

dict_items([('name', 'oshan'), ('roll_no', 28)])

# 1.13) Check Key Exists

In [142]:
"name" in student

True

# 1.13) Get Length of Dictionary

In [143]:
len(student)

2

# 1.14) Loop Through Keys

In [144]:
for k in student :
    print(k)

name
roll_no

# 1.15) Loop Through Values

In [145]:
for i in student.values():
    print(i)

oshan
28

# 1.16)Loop Through Items

In [146]:
for i,j in student.items():
    print(i,j)

name oshan
roll_no 28

# 2) Working with Pandas DataFrame

# 1.1 Create a DataFrame containing student details such as Name, Age, and Marks.
`Syntax : df = pd.DataFrame()`

In [147]:
# %pip install pandas
import pandas as pd
list1 = {
    "Name" : ["Oshan","Sudeep","Sworup", "Bibek","Alok","Manish"],
    "Age" : [22,20,21,23,23,22],
    "Mark" : [90, 99, 85, 88, 91, 87]

}

df = pd .DataFrame(list1)

# 2.2) Display the first 5 rows of the DataFrame.
` Syntax : df.head()`

In [148]:
df.head()

     Name  Age  Mark
0   Oshan   22    90
1  Sudeep   20    99
2  Sworup   21    85
3   Bibek   23    88
4    Alok   23    91

# 2.3)Display the last 5 rows of the DataFrame.

`Syntax :df.tail()`

In [149]:
df.tail()

     Name  Age  Mark
1  Sudeep   20    99
2  Sworup   21    85
3   Bibek   23    88
4    Alok   23    91
5  Manish   22    87

# 2.4)Find the total number of rows and columns in the DataFrame.
` Syntax: df.shape`

In [150]:
df.shape

(6, 3)

# 2.5) Display all column names in the DataFrame
` Syntax : df.columns`

In [151]:
df.columns

Index(['Name', 'Age', 'Mark'], dtype='str')

# 2.6)Display complete information about the DataFrame including data types and memory usage.
` Syntax : df.info() `

In [152]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Mark    6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

# 2.7)Generate a statistical summary of numerical columns in the DataFrame.
` Syntax : df.describe() `

In [153]:
df.describe()

             Age       Mark
count   6.000000   6.000000
mean   21.833333  90.000000
std     1.169045   4.898979
min    20.000000  85.000000
25%    21.250000  87.250000
50%    22.000000  89.000000
75%    22.750000  90.750000
max    23.000000  99.000000

# 2.8) Select and display the Name column from the DataFrame.
` Syntax : df[key] `

In [154]:
df['Name']

0     Oshan
1    Sudeep
2    Sworup
3     Bibek
4      Alok
5    Manish
Name: Name, dtype: str

# 2.9) Select and display multiple columns such as Name and Marks.
` Syntax :  df[[keys,keys'....]]`

In [155]:
df[['Name', 'Mark']]

     Name  Mark
0   Oshan    90
1  Sudeep    99
2  Sworup    85
3   Bibek    88
4    Alok    91
5  Manish    87

# 2.10) Display the first row of the DataFrame using positional indexing.
` Syntax : df.iloc[0] `

In [156]:
df.iloc[0]

Name    Oshan
Age        22
Mark       90
Name: 0, dtype: object

# 2.11) Display the first row of the DataFrame using label-based indexing.
` Syntax : df.loc[0]`

In [157]:
df.loc[0]

Name    Oshan
Age        22
Mark       90
Name: 0, dtype: object

# 2.12) Access a specific cell value such as Marks of the first student.
` Syntax : df.loc[0,keys;]`

In [158]:
df.loc[0,'Mark']

np.int64(90)

# 2.13) Filter and display students whose Marks are greater than 80.
` Syntax : df[df['keys'] > 80]`

In [159]:
df[df['Mark'] > 80]

     Name  Age  Mark
0   Oshan   22    90
1  Sudeep   20    99
2  Sworup   21    85
3   Bibek   23    88
4    Alok   23    91
5  Manish   22    87

# 2.14) Filter and display students whose Age is greater than 20 and Marks are greater than 75.
` Syntax : df[(df['keys'] > 20) & (df['keys'] > 75)] `

In [160]:
df[(df['Age'] > 20) & (df['Mark'] > 75)]

     Name  Age  Mark
0   Oshan   22    90
2  Sworup   21    85
3   Bibek   23    88
4    Alok   23    91
5  Manish   22    87

# 2.15) Add a new column called Grade to the DataFrame.
` Syntax : df['keys'] = ['A','B']`

In [161]:

df['keys'] = ['A', 'B', 'C', 'D', 'E', 'F']
df

     Name  Age  Mark keys
0   Oshan   22    90    A
1  Sudeep   20    99    B
2  Sworup   21    85    C
3   Bibek   23    88    D
4    Alok   23    91    E
5  Manish   22    87    F

# 2.16) Increase all students’ Marks by 5.
` Syntax : df['Marks'] = df['Mark'] + 5`

In [162]:
df['Mark'] = df['Mark'] + 5
df

     Name  Age  Mark keys
0   Oshan   22    95    A
1  Sudeep   20   104    B
2  Sworup   21    90    C
3   Bibek   23    93    D
4    Alok   23    96    E
5  Manish   22    92    F

# 2.17) Update the Marks of Ram to 95 using a condition.
` Syntax : df.loc[df['Name']=='Ram','Marks'] =
95`

In [163]:
df.loc[df['Name'] == 'Oshan', 'Mark'] = 95
df

     Name  Age  Mark keys
0   Oshan   22    95    A
1  Sudeep   20   104    B
2  Sworup   21    90    C
3   Bibek   23    93    D
4    Alok   23    96    E
5  Manish   22    92    F

# 2.18) Remove the Age column from the DataFrame.
` Syntax : df.drop('Age', axis=1)`

In [164]:
df.drop('Age', axis=1)

     Name  Mark keys
0   Oshan    95    A
1  Sudeep   104    B
2  Sworup    90    C
3   Bibek    93    D
4    Alok    96    E
5  Manish    92    F

# 2.19) Remove the first row from the DataFrame.
` Syntax : df.drop(0, axis=0)`

In [165]:
df.drop(0, axis=0)

     Name  Age  Mark keys
1  Sudeep   20   104    B
2  Sworup   21    90    C
3   Bibek   23    93    D
4    Alok   23    96    E
5  Manish   22    92    F

# 2.20) Sort the DataFrame by Marks in ascending order.
` Syntax : df.sort_values('Marks')`

In [166]:
df.sort_values('Mark')

     Name  Age  Mark keys
2  Sworup   21    90    C
5  Manish   22    92    F
3   Bibek   23    93    D
0   Oshan   22    95    A
4    Alok   23    96    E
1  Sudeep   20   104    B

# 2.21) Concatenate two DataFrames vertically.
`Syntax : pd.concat([df1, df2])`

In [167]:
list2 = {
    "Name": ["Ram", "Shyam", "Hari", "Sita", "Gita", "Ramesh"],
    "Age": [21, 22, 20, 23, 21, 24],
    "Mark": [78, 85, 92, 88, 95, 80]
}

df1 = pd.DataFrame(list2)
pd.concat([df,df1])

     Name  Age  Mark keys
0   Oshan   22    95    A
1  Sudeep   20   104    B
2  Sworup   21    90    C
3   Bibek   23    93    D
4    Alok   23    96    E
5  Manish   22    92    F
0     Ram   21    78  NaN
1   Shyam   22    85  NaN
2    Hari   20    92  NaN
3    Sita   23    88  NaN
4    Gita   21    95  NaN
5  Ramesh   24    80  NaN

# 2.22)Read data from a CSV file into a DataFrame.
`Syntax : pd.read_csv('file.csv') `

In [168]:
pd.read_csv('StudentData1.csv')  #from file name
#pd.read_csv(r'C:\Users\user\Desktop\Machine Learning\Lab2\StudentData1.csv') # from file location

       Name  Age  Mark
0     Oshan   22    90
1    Sudeep   20    99
2    Sworup   21    85
3     Bibek   23    88
4      Alok   23    91
5    Manish   22    87
6       Ram   21    78
7     Shyam   22    84
8      Hari   20    92
9      Sita   23    89
10     Gita   21    95
11   Ramesh   24    80
12    Nabin   22    86
13  Prakash   23    82
14    Anish   21    93

# 2.23) Write the DataFrame into a CSV file.
`Syntax : df.to_csv('file.csv') `

In [169]:
df.to_csv('StudentData2.cvs')

# 2.24)  Read data from an Excel file into a DataFrame.
`Syntax : pd.read_excel('file.xlsx') `

In [170]:
# %pip install openpyxl
pd.read_excel('excleStudentData2.xlsx')

       Name  Age  Mark
0     Oshan   22    90
1    Sudeep   20    99
2    Sworup   21    85
3     Bibek   23    88
4      Alok   23    91
5    Manish   22    87
6       Ram   21    78
7     Shyam   22    84
8      Hari   20    92
9      Sita   23    89
10     Gita   21    95
11   Ramesh   24    80
12    Nabin   22    86
13  Prakash   23    82
14    Anish   21    93

# 2.25)  Write the DataFrame into an Excel file.
`Syntax : df.to_excel('file.xlsx')`

In [171]:
df.to_excel('excleStudentData1.xlsx')